.catalog:
  name: "Drupal"
  version: "8.0.1"
  description: "Blog tool, publishing platform and CMS"
  uuid: Drupal
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access the drupal site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"

drupal-8:
